services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    container_name: web
    command: sh -c "./scripts/wait-for-it.sh postgres:5432 -- alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=prod
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
